---

- name: Determine if the Fedora Toolbox repository needs to be added to Karaf
  find: paths="{{ karaf_home }}/data/cache" contains="{{ karaf_fctools_repoadd }}" recurse=yes
  register: fc_toolbox_repo_status
  changed_when: "fc_toolbox_repo_status.files == 0"

- name: Install Fedora Toolbox repository in Karaf
  command: "{{ karaf_home }}/bin/client feature:repo-add {{ karaf_fctools_repoadd }}"
  when: fc_toolbox_repo_status.files == 0
